from typing import Protocol
from typing import Any
from typing import List
class Repository(Protocol):
    def save(self,data:Any)->None:
        ...
    def get(self,id:str)->Any:
        ...
    def update(self,id:str,data:Any)->None:
        ...
    def insert(self,data:Any)->None:
        ...
    def execute(self,query:str)->List[Any]:
        ...